/// Every command the plugin exposes over the Tauri IPC.
///
/// `tauri-plugin` turns each name into an `allow-<name>` / `deny-<name>`
/// permission under `permissions/autogenerated/`, so a command added to the
/// invoke handler but not here is unreachable from the webview rather than
/// silently ungated.
const COMMANDS: &[&str] = &["log", "export_spans"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
